/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import core.Variables;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author funes
 */
public class FormularioConfiguracionAvanzada extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioConfiguracion
     */
    public FormularioConfiguracionAvanzada() {
        initComponents();
        
        lblUrlDB.setText("Actual: "+Variables.urlDB);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfUrlDB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfUsuarioDB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfClaveDB = new javax.swing.JTextField();
        btnActualizarUrl = new javax.swing.JButton();
        btnActualizarUsuario = new javax.swing.JButton();
        btnActualizarClave = new javax.swing.JButton();
        lblUrlDB = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Configuracion de la Base de datos (Manipular con cuidado)");

        jLabel2.setText("URL de la base de datos");

        jLabel3.setText("Usuario de la DB");

        jLabel4.setText("Clave del usuario");

        btnActualizarUrl.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarUrl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar_32x32.png"))); // NOI18N
        btnActualizarUrl.setText("Actualizar URL");
        btnActualizarUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUrlActionPerformed(evt);
            }
        });

        btnActualizarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar_32x32.png"))); // NOI18N
        btnActualizarUsuario.setText("Actualizar usuario");
        btnActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarUsuarioActionPerformed(evt);
            }
        });

        btnActualizarClave.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar_32x32.png"))); // NOI18N
        btnActualizarClave.setText("Actualizar clave");
        btnActualizarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClaveActionPerformed(evt);
            }
        });

        lblUrlDB.setText("Actual: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfUrlDB, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarUrl))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblUrlDB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfUsuarioDB, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarUsuario))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfClaveDB, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarClave))
                    .addComponent(jLabel4))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUrlDB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUrlDB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarUrl))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsuarioDB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarUsuario))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfClaveDB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarClave))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUrlActionPerformed
        // TODO add your handling code here:
        
        
        try{
            Variables.urlDB=tfUrlDB.getText();
            
            lblUrlDB.setText("Actual: "+Variables.urlDB);
            tfUrlDB.setText("");
            
            Variables.rutaDB=Variables.configuracionDriver+Variables.urlDB;
            
            File file = new File(System.getProperty("user.dir")+"\\archivos\\DB.txt");
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            bw.write(Variables.urlDB);
            
            bw.close();
            
            JOptionPane.showInternalMessageDialog(rootPane, "Acción ejecutada","Información",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error en la escritura. Contacte a su administrador"+e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarUrlActionPerformed

    private void btnActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuarioActionPerformed
        // TODO add your handling code here:
        try{
            Variables.userDB=tfUsuarioDB.getText();

            File file = new File(System.getProperty("user.dir")+"\\archivos\\USER.txt");
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(Variables.userDB);

            bw.close();

            JOptionPane.showInternalMessageDialog(rootPane, "Acción ejecutada","Información",JOptionPane.INFORMATION_MESSAGE);
            tfUsuarioDB.setText("");
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error en la escritura. Contacte a su administrador"+e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarUsuarioActionPerformed

    private void btnActualizarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClaveActionPerformed
        // TODO add your handling code here:
        try{
            Variables.claveDB=tfClaveDB.getText();

            File file = new File(System.getProperty("user.dir")+"\\archivos\\PASS.txt");
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            bw.write(Variables.claveDB);

            bw.close();

            JOptionPane.showInternalMessageDialog(rootPane, "Acción ejecutada","Información",JOptionPane.INFORMATION_MESSAGE);
            tfClaveDB.setText("");
        
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error en la escritura. Contacte a su administrador"+e.getMessage());
        }
    }//GEN-LAST:event_btnActualizarClaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarClave;
    private javax.swing.JButton btnActualizarUrl;
    private javax.swing.JButton btnActualizarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblUrlDB;
    private javax.swing.JTextField tfClaveDB;
    private javax.swing.JTextField tfUrlDB;
    private javax.swing.JTextField tfUsuarioDB;
    // End of variables declaration//GEN-END:variables
}
